redsolutioncms/templates/redsolutioncms/project/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, include, handler404, handler500, url
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap

handler404
handler500

admin.autodiscover()
urlpatterns = patterns('')

sitemaps = {
}

if settings.DEBUG:
    pass

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^robots.txt$', 'django.views.generic.simple.direct_to_template', {'template': 'robots.txt', 'mimetype': 'text/plain'}),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

redsolutioncms/templates/redsolutioncms/urls.py
# -*- coding: utf-8 -*-
from urls import *

urlpatterns += patterns('',{% for package in cms_settings.packages.installed %}{% for entry_point in package.entry_points.has_urls %}
    (r'^custom/{{ entry_point.module }}$', include('{{ entry_point.module }}.urls')),{% endfor %}{% endfor %}
)

redsolutioncms/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, include, url, handler404, handler500
from django.conf import settings

handler404
handler500

urlpatterns = patterns('')

if settings.DEBUG:
    from django.contrib import admin
    admin.autodiscover()

    urlpatterns += patterns('',
        (r'^admin/', include(admin.site.urls)),
    )
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

urlpatterns += patterns(
    '',
    url(r'^$', 'redsolutioncms.views.index', name='index'),
    url(r'^apps$', 'redsolutioncms.views.apps', name='apps'),
    url(r'^load$', 'redsolutioncms.views.load', name='load'),
    url(r'^restart$', 'redsolutioncms.views.restart', name='restart'),
    url(r'^started/$', 'redsolutioncms.views.started', name='started'),
    url(r'^custom$', 'redsolutioncms.views.custom', name='custom'),
    url(r'^build$', 'redsolutioncms.views.build', name='build'),
    url(r'^done$', 'redsolutioncms.views.done', name='done'),
    url(r'^cancel_lock/$', 'redsolutioncms.views.cancel_lock', name='cancel_lock'),
    url(r'^create_superuser/$', 'redsolutioncms.views.create_superuser', name='create_superuser'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
        {'packages': ('django.conf',)}, name='admin_jsi18n'),
)

try:
    from urls_additional import *
except ImportError:
    print 'Can not import urls_additional!'

redsolutioncms/models.py
# -*- coding: utf-8 -*-
import os
import shutil
from os.path import abspath, join, dirname, isdir, isfile, exists
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.template.loader import render_to_string
from django.core.exceptions import ObjectDoesNotExist
from django.db.models.signals import post_syncdb
from redsolutioncms.loader import home_dir, project_dir

# utility
def merge_dirs(src, dst):
    '''Recursive merge directories'''
    for root, dirs, files in os.walk(src):
        rel_path = root.replace(src, '')
        rel_path = rel_path.lstrip(os.path.sep)
        for file in files:
            shutil.copy(
                join(root, file),
                join(dst, rel_path)
            )
        for dir in dirs:
            if not exists(join(dst, rel_path, dir)):
                os.mkdir(join(dst, rel_path, dir))

class BaseSettingsManager(models.Manager):
    def get_settings(self):
        if self.get_query_set().count():
            return self.get_query_set()[0]
        else:
            return self.get_query_set().create()

class BaseSettings(models.Model):
    class Meta:
        abstract = True
    objects = BaseSettingsManager()

class CMSSettings(BaseSettings):
    DATABASE_ENGINES = [
        ('postgresql_psycopg2', 'postgresql_psycopg2',),
        ('postgresql', 'postgresql',),
        ('mysql', 'mysql',),
        ('sqlite3', 'sqlite3',),
    ]

    project_name = models.CharField(verbose_name=_('Project name'),
        max_length=50, default='myproject', help_text=_('Invent a project name'))
    domain = models.CharField(verbose_name=_('Desired domain'),
        max_length=50, default='myproject.com', help_text=_('Enter your site domain for configuration'))
    database_engine = models.CharField(verbose_name=_('Database engine'),
        max_length=50, choices=DATABASE_ENGINES, default='sqlite3')
    database_name = models.CharField(verbose_name=_('Database name'),
        max_length=50, default='myproject.sqlite', help_text=_('In case of sqlite3, database filename'))
    database_user = models.CharField(verbose_name=_('Database user'),
        max_length=50, blank=True, default='', help_text=_('Not used with sqlite3'))
    database_password = models.CharField(verbose_name=_('Database password'),
        max_length=50, blank=True, default='', help_text=_('Not used with sqlite3'))
    database_host = models.CharField(verbose_name=_('Database host'),
        max_length=50, blank=True, default='', help_text=_('Not used with sqlite3'))
    database_port = models.IntegerField(verbose_name=_('Database port'),
        blank=True, null=True, help_text=_('Not used with sqlite3'))
    # hidden fields
    initialized = models.BooleanField(verbose_name=_('CMS was initialized'), default=False)
    base_template = models.CharField(verbose_name=_('Base template'), max_length=50, blank=True, default='')
    frontpage_handler = models.ForeignKey('CMSEntryPoint', related_name='settings', null=True)

    def render_to(self, file_name, template_name, dictionary=None, mode='a+'):
        """
        ``file_name`` is relative path to destination file.
            It can be list or tuple to be os.path.joined
            To make settings.py use: 'settings.py'
            To make template use: ['..', 'templates', 'base.html']
            To make media use: ['..', 'media', 'css', 'style.css']
        
        ``template_name`` is name of template to be rendered.
        
        ``dictionary`` is context dictionary.
            ``cms_settings`` variable always will be add to context.
        
         ``mode`` is mode in witch destination file will be opened.
             Use 'w' to override old content.
        """
        if isinstance(file_name, (tuple, list)):
            file_name = join(*file_name)
        file_name = join(project_dir, self.project_name, file_name)
        try:
            os.makedirs(dirname(file_name))
        except OSError:
            pass
        if dictionary is None:
            dictionary = {}
        dictionary['cms_settings'] = self
        value = render_to_string(template_name, dictionary)
        value = value.encode('utf-8')
        open(file_name, mode).write(value)

    def copy_to(self, dst, src, merge=True, mode='wb'):
        """
        Deprecated. Use ``copy_dir`` or ``copy_file`` instead.
        Copies directory or file with mergig directories capability.
        If ``src`` is regular file, copy it in ``dst`` file or ``dst`` dir.
        If ``src`` is directory, ``dst`` must be directory or must not exist.
        If ``dst`` dir exists, merge or replace it with ``src`` content, 
        depending on ``merge`` argument
        
        Example:
        cms_settings.copy_to(os.path.join(project_media, 'img'), path_to_images)
        """
        import warnings
        warnings.warn('Deprecated. Use ``copy_dir`` or ``copy_file`` instead.')

        # first, check ``src``
        if isfile(src):
            self.copy_file(dst, src, mode)
        if isdir(src):
            self.copy_dir(dst, src, merge)
    
    def copy_file(self, dst, src, mode='wb'):
        '''
        Copy or append file content.
        Mode 'w' is for file rewriting, 'a' for appending to the end of file
        '''
        # silently try to make parent dir
        try:
            os.makedirs(dirname(dst))
        except OSError:
            pass
        if not exists(dst):
            shutil.copy(src, dst)
        else:
            dst_file = open(dst, mode)
            src_file = open(src, 'r')
            dst_file.write(src_file.read())
            dst_file.close()
            src_file.close()
        
    def copy_dir(self, dst, src, merge=True):
        '''
        Copy whole dir recursively.
        When merge=True, target directory will not be deleted,
        othwerwise, it will.
        '''
        if exists(dst):
            if isdir(dst):
                if not merge:
                    shutil.rmtree(dst)
                    shutil.copytree(src, dst)
                else:
                    merge_dirs(src, dst)
            else:
                raise IOError('Error: ``dst`` is not dir')
        else:
            shutil.copytree(src, dst)

    def package_was_installed(self, package_name):
        return package_name in self.installed_packages

    @property
    def installed_packages(self):
        return self.packages.installed().values_list('package', flat=True)

    @property
    def project_dir(self):
        import warnings
        warnings.warn('Project dir is deprecated attribute. Use redsolutioncms.loader.project_dir instead')
        return project_dir

    @property
    def temp_dir(self):
        import warnings
        warnings.warn('Project dir is deprecated attribute. Use redsolutioncms.loader.home_dir instead')
        return home_dir

class PackageManager(models.Manager):

    def installed(self):
        return self.get_query_set().filter(installed=True)

    def modules(self):
        return self.get_query_set().exclude(category__name='templates')

    def templates(self):
        return self.get_query_set().filter(category__name='templates')

class CMSPackage(models.Model):
    class Meta:
        unique_together = (
            ('settings', 'package',),
        )
    settings = models.ForeignKey(CMSSettings, related_name='packages')

    selected = models.BooleanField(verbose_name=_('Selected'), default=False)
    package = models.CharField(verbose_name=_('Package'), max_length=255)
    version = models.CharField(verbose_name=_('Package version'), max_length=50)
    verbose_name = models.CharField(verbose_name=_('Verbose name'), max_length=255)
    description = models.TextField(verbose_name=_('Description'))
    path = models.CharField(verbose_name=_('Installed to path'), max_length=255, blank=True, null=True)
    installed = models.BooleanField(verbose_name=_('Was successfully installed'), default=False)
    category = models.ForeignKey('Category', null=True, related_name='packages')

    screenshot = models.URLField(verbose_name=_('Screenshot preview URL'), null=True)

    objects = PackageManager()

    def __unicode__(self):
        return self.package

class CategoryManager(models.Manager):

    def templates(self):
        return self.get_query_set().filter(name='templates')

    def required(self):
        return self.get_query_set().filter(required=True)


class Category(models.Model):
    '''Category for package'''

    class Meta:
        ordering = ['-required', 'id']

    settings = models.ForeignKey(CMSSettings, related_name='categories')
    name = models.CharField(verbose_name=_('Category name'), max_length=255)
    parent = models.ForeignKey('self', null=True)
    required = models.BooleanField(verbose_name=_('Mandatory category'), default=False)

    def __unicode__(self):
        return self.name

    def verbose_name(self):
        '''
        Hardcoded categories names 
        '''
        verbose_names = {
            'frontpage': _('Frontpage handlers'),
            'content': _('Content plugins'),
            'utilities': _('Utilities'),
            'templates': _('Templates for site'),
            'other': _('Other applications'),
        }
        return verbose_names.get(self.name, self.name)

class EntryPointManager(models.Manager):
    def has_urls(self):
        return self.get_query_set().filter(has_urls=True)

    def frontpage_handlers(self):
        return self.get_query_set().filter(frontpage_handler=True)

class CMSEntryPoint(models.Model):
    package = models.ForeignKey(CMSPackage, related_name='entry_points')
    module = models.CharField(verbose_name=_('Module name'), max_length=255)
    has_urls = models.BooleanField(verbose_name=_('Has urls'))
    frontpage_handler = models.BooleanField(verbose_name=_('Can handle frontpage'))

    objects = EntryPointManager()

    def __unicode__(self):
        return 'Entry point %s' % self.module

class CMSCreatedModel(models.Model):

redsolutioncms/templates/redsolutioncms/apps.html
{% extends "redsolutioncms/base.html" %}
{% load i18n %}

{% block script %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script>
$(document).ready(function(){
	$('#select_all').click(function(){
		$(':checkbox').attr('checked','checked');
		return false;
	});
	$('#select_none').click(function(){
		$(':checkbox').removeAttr('checked');
		return false;
	});
	// $('input:checkbox').bind('change', function(event){
	//     var status = $(this).attr('checked');
	//     var element_class = $(this).attr('class');
	//     $('.'+element_class).each(function(){
	//       $(this).attr('checked', status);});
	//   });
	$('.screenshots label').each(function(){
	  if ($(this).find('input:radio').length) {
	    var text = $(this).text();
	    var input = $(this).find('input:radio');
	    $(this).text('');
	    $(this).append(input).append('<img src="' + text + '" />');
	  }
	});
});
</script>

{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="/">{% trans 'Start' %}</a> » 
<strong>{% trans 'Application list' %}</strong> »
{% trans 'Site config' %} »
{% trans 'Creating superuser' %}
</div>
{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data" action="">
    <p>{% trans 'Select' %} <a href="#" link="self" id="select_all"> {% trans 'all' %}</a>
    <a href="#" link="self" id="select_none">{% trans 'none' %}</a>
    {{ formset.management_form }}
    {% for form in formset.forms %}
      <h2>{{ form.instance.verbose_name }}</h2>
      {% if form.instance.name == 'templates' %}
          <table class="screenshots">
            {{ form.as_table }}  
          </table>
      {% else %}
          <table>
            {{ form.as_table }}
          </table>
      {% endif %}
    {% endfor %}
    <input type="button" value="{% trans 'Back' %}" class="input-bg floated-button" onclick="javascript:document.location='{% url index %}';"/>
    <input type="submit" value="{% trans 'Next' %}" class="input-bg floated-button" />
</form>
{% endblock %}

redsolutioncms/templates/redsolutioncms/base.html
{% extends "admin/base.html" %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="/media/css/style.css" />
    <link rel="shortcut icon" href="/favicon.ico" />
{% block script %}{% endblock %}
{% endblock %}
{% block userlinks %}{% endblock %}
{% block branding %}
<div class="logo">
    <div class="logo-top">
      <a href="http://redsolutioncms.org/">
        <span class="red">red</span><span class="solution">solution</span>
      </a>
    </div>
    <div class="logo-bottom"><a href="http://redsolutioncms.org/">content management system</a></div>
</div>
{% endblock %}

redsolutioncms/templates/redsolutioncms/build.html
{% extends "redsolutioncms/base.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="/">{% trans 'Start' %}</a> »
<a href="{% url apps %}">{% trans 'Application list' %}</a> »
<a href="{% url custom %}">{% trans 'Site config' %}</a> »
<strong>{% trans 'Creating superuser' %}</strong>
</div>
{% endblock %}

{% block content %}
<h2>{% trans "Now I'm gonna to create superuser for your site" %}</h2>
<form method="post" enctype="multipart/form-data" action="">
    <table>
    {{ form }}
    </table>
    <p>{% trans 'To create superuser manually, run in console' %}</p>
    <pre>
{{ django }} createsuperuser
    </pre>
    <input type="button" value="{% trans 'Back' %}" class="input-bg floated-button" onclick="javascript:document.location='{% url custom %}';"/>
    <input type="button" value="{% trans 'Skip' %}" class="input-bg floated-button" onclick="javascript:document.location='{% url done %}';"/>
    <input type="submit" value="{% trans 'Next' %}" class="input-bg floated-button" />
</form>
{% endblock %}

redsolutioncms/templates/redsolutioncms/custom.html
{% extends "redsolutioncms/base.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="/">{% trans 'Start' %}</a> »
<a href="{% url apps %}">{% trans 'Application list' %}</a> »
<strong>{% trans 'Site config' %}</strong> »
{% trans 'Creating superuser' %}
</div>
{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data" action="">
    <table>
        <tr><th>{% trans 'Packages' %}</th><th>{% trans 'Settings' %}</th></tr>
        {% for package in cms_settings.packages.installed %}
            <tr>
                <td>{{ package.verbose_name }}</td>
                <td>
                {% for entry_point in package.entry_points.has_urls %}
                    <a href="{% url custom %}/{{ entry_point.module }}">{% trans 'Settings for' %} {{ entry_point.module }}</a></td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
    
    {{ frontpage_form.as_p }}
    <a href="{% url apps %}" class="button-link floated-button">{% trans 'Back' %}</a>
    <input type="submit" value="{% trans 'Make' %}" class="input-bg floated-button" />
</form>
{% endblock %}

redsolutioncms/templates/redsolutioncms/done.html
{% extends "redsolutioncms/base.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="/">{% trans 'Start' %}</a> »
<a href="{% url apps %}">{% trans 'Application list' %}</a> »
<a href="{% url custom %}">{% trans 'Site config' %}</a> »
<a href="{% url create_superuser %}">{% trans 'Creating superuser' %}</a>
</div>
{% endblock %}


{% block content %}
<h2>{% trans 'Everything ready for start now' %}</h2>

<h3>{% trans "Now project is ready. You're welcome to check it out" %}</h3>
    
<a class="button-link floated-button" href="http://127.0.0.1:8001/admin/">
  {% trans 'Admin your site' %}
</a>
<a class="button-link floated-button" href="http://127.0.0.1:8001/">
  {% trans 'View content' %}
</a>

<div class="clear" />
<h3>{% trans 'After all, you can run development version of your site manually' %}</h3>
<p>{% trans "To do this, run in console" %}</p>
<pre>
{{ django }} runserver 8001
</pre>
<p>{% trans 'Then your project will be available at: ' %}<a href="http://127.0.0.1:8001">http://127.0.0.1:8001</a></p>
<p>{% trans 'Your admin will be available at: ' %}<a href="http://127.0.0.1:8001/admin/">http://127.0.0.1:8001/admin/</a></p>


{% endblock %}

redsolutioncms/templates/redsolutioncms/error.html
{% extends "redsolutioncms/base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans 'SUDDENLY!' %}</h2>
<p>
{% trans "Suddenly, you see an error in CMS. This situation souldn't appears if everything going fine." %}
<br />
{% trans 'So, something going wrong' %}:</p>
<ul class="errorlist">
    <li>{{ error }}</li>
</div>
{% endblock %}

redsolutioncms/templates/redsolutioncms/index.html
{% extends "redsolutioncms/base.html" %}
{% load i18n %}

{% block script %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script>
$(document).ready(function(){
$('#id_database_engine').bind('change', function(){
 
  var dbname = $('#id_database_name').val();
  var pattern1 = /(\w+)\.\w+/;
  var pattern2 = /(\w+)\.sqlite/;
  
  if ($(this).val() == 'sqlite3') {
    if (!(dbname.match(pattern1))) {
      /* if dbname didn't look like file, add .sqlite extension */  
      $('#id_database_name').val(dbname + '.sqlite');
    }
    // Disable fields
    $('#id_database_user').attr('disabled', 'disabled');
    $('#id_database_password').attr('disabled', 'disabled');
    $('#id_database_host').attr('disabled', 'disabled');
    $('#id_database_port').attr('disabled', 'disabled');
  } else {
    /* otherwise, remove sqlite extensnion */
    if (dbname.match(pattern2)) {
      $('#id_database_name').val(dbname.match(pattern2)[1]);
    }
    // Enabled fields
    $('#id_database_user').removeAttr('disabled');
    $('#id_database_password').removeAttr('disabled');
    $('#id_database_host').removeAttr('disabled');
    $('#id_database_port').removeAttr('disabled');
  }
  // Set default values for database
    switch ($(this).val()){
      case 'postgresql':
      case 'postgresql_psycopg2':
          $('#id_database_port').attr('value', '5432');
          break;
      case 'mysql':
          $('#id_database_port').attr('value', '3306');
          break;
      case 'sqlite3':
          $('#id_database_user').attr('value', '');
          $('#id_database_password').attr('value', '');
          $('#id_database_host').attr('value', '');
          $('#id_database_port').attr('value', '');
          break;
    }
  
});
$('#id_project_name').bind('change', function(){
  $('#id_domain').val($(this).val() + '.com');
});
$('#id_database_engine').trigger('change');
});
</script>

{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="/">{% trans 'Start' %}</a> »
{% trans 'Application list' %} »
{% trans 'Site config' %} »
{% trans 'Creating superuser' %}
</div>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" action="">
        <table id="start">
            {{ form.as_table }}
        </table>
    <input type="submit" value="{% trans 'Next' %}" class="input-bg floated-button" />
    </form>
{% endblock %}

redsolutioncms/templates/redsolutioncms/wait.html
{% extends "redsolutioncms/base.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
{% trans 'Redirect pending' %}
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/media/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="http://redsolutioncms.org/tips.js"></script>
<script type="text/javascript">
var tips = [
    '<div class="tip">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</div>',
    '<div class="tip">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>',
    '<div class="tip">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</div>',
];

$(document).ready(function(){
    function ping() {
        $.ajax({
            type: 'POST',
            url: "{% url started %}",
            data: {task_id: "{{ start_task_id }}"},
            error: function(a, b, c) {
                setTimeout(ping, 1000);
            },             
            success: function(data) {
                window.location = "{{ redirect_to }}";
            }
        });
    }
    function restart() {
        $.ajax({
            type: 'POST',
            url: "{% url cancel_lock %}",
            data: { task_id: "{{ task_id }}"},
            error: function(data) {
                setTimeout(ping, 5000);
            },
            success: function(data) {
                setTimeout(ping, 5000);
            }
        });
    }
    restart();
    
    /*  tips  and tricks workaround */
    $('#tips').html(tips[0]);
    var number = 0;
    function next_tip(){
            number++;
            if (number == tips.length){number=0;};
            $('#tips').html(tips[number]);
            setTimeout(next_tip, 10000);
        };
    setTimeout(next_tip, 10000);
});
</script>
{% endblock %}

{% block content %}
  <img src="/media/img/loading.gif" /><p>{% trans 'Wait please...' %}</p>
  <div id="tips"></div>
{% endblock %}